apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: js00zfm4r-go-gitops
  description: This is GitOps manifest for js00zfm4r-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: js00zfm4r-go
    janus-idp.io/tekton: js00zfm4r-go 
    backstage.io/kubernetes-id: js00zfm4r-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:js00zfm4r-go
