apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: js00zfm4r-go
  janus-idp.io/tekton: js00zfm4r-go
  backstage.io/kubernetes-id: js00zfm4r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: js00zfm4r-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
