apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: js00zfm4r-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:1a4f5a2ca1c7bb4c42bebbddb5b2ebf70242498f@sha256:c1caea9651fa7978accd4741e70ca4d2c4f8988ae2ed2473d4f6293f9495b2a7
          name: container-image
